"use strict";

module.exports = {
    inclusionThreshold: 12,
    semanticScoreMultiplier: 0.4,
    fallbackThresholdDelta: 2,
    fallbackMinCandidates: 6,
    adaptiveThreshold: {
        enabled: true,
        broadEventPreferredCategoryCount: 10,
        broadDepartmentCount: 3,
        broadEventDelta: -1,
    },
    fieldWeights: {
        color: 4,
        occasion: 4,
        ethnicity: 4,
        pattern: 3,
        activity: 3,
        fit: 3,
        style: 3,
        theme: 2,
        material: 2,
        detail: 2,
        neckline: 2,
        length: 2,
        transparency: 1,
        hemline_style: 1,
        size_group: 1,
    },
    activityPenalties: {
        loungewear: -4,
        sleepwear: -5,
        "basic-casual": -3,
        "beach-and-resort": -3,
        "leisure-sport": -2,
        athleisure: -2,
    },
    occasionPenalties: {
        casual: -3,
        "basic-casual": -3,
    },
    tokenCanonicalMap: {
        tshirt: "t-shirt",
        tshirts: "t-shirt",
        "t-shirts": "t-shirt",
        tshirtss: "t-shirt",
        sequin: "sequins",
        geometrical: "geometric",
        oversized: "over-sized",
        "fit&flare": "fit-and-flare",
        fitnflare: "fit-and-flare",
    },
    semanticGroups: {
        color: [
            ["red", "maroon", "burgundy", "crimson", "scarlet", "ruby", "wine", "deep-red"],
            ["pink", "blush", "dusty-rose", "fuchsia", "hot-pink", "magenta", "rose-pink"],
            ["orange", "rust", "burnt-orange", "tangerine", "saffron", "marigold"],
            ["yellow", "mustard", "gold", "turmeric", "caramel"],
            ["green", "dark-green", "olive", "sage", "teal", "emerald-green", "forest-green", "lime-green", "bottle-green"],
            ["blue", "navy", "indigo", "cobalt", "royal-blue", "sapphire", "deep-blue", "sky-blue", "powder-blue"],
            ["purple", "lavender", "violet", "deep-plum", "lilac"],
            ["white", "off-white", "cream", "ivory", "pearl-white", "champagne"],
            ["grey", "charcoal-grey", "light-grey", "slate-grey", "silver"],
            ["brown", "tan", "beige", "khaki", "caramel", "mocha", "toffee", "light-brown"],
            ["black", "charcoal"],
            ["multi", "multicolor"],
        ],
        pattern: [
            ["floral", "botanical", "leaf-print", "flower"],
            ["geometric", "abstract", "diagonal-stripes", "horizontal-stripes", "vertical-stripes", "checks", "gingham", "mini-checks", "color-block"],
            ["embroidered", "embellished", "sequins", "sequin", "shimmer", "lace", "cut-work"],
            ["ethnic-motif", "printed", "statement-print", "abstract"],
            ["solid", "self-design"],
        ],
        fit: [
            ["relaxed", "loose", "oversized", "baggy"],
            ["slim", "skinny", "slim-fit", "skinny-fit"],
            ["regular", "regular-fit"],
        ],
        style: [
            ["over-sized", "baggy", "boxy", "loose-fit", "relaxed"],
            ["slim-fit", "skinny-fit", "tailored", "sheath"],
            ["wide-leg", "flared", "bell-bottom", "trapeze"],
            ["straight-fit", "regular-fit", "a-line"],
            ["cargo", "relaxed"],
        ],
        material: [
            ["cotton", "100%-cotton", "cotton-blend", "cotton-poly-blend", "cotton-lycra-blend", "cotton-rayon-blend", "cotton-viscose-blend", "cotton-linen-blend", "cotton-tencel-blend"],
            ["rayon", "viscose-rayon", "100%-rayon"],
            ["linen", "linen-blend"],
            ["polyester", "100%-polyester", "poly-blend"],
            ["nylon", "nylon-elastane", "polyamide-spandex"],
            ["satin", "silk-feel", "georgette-feel", "chiffon-feel"],
            ["leather", "synthetic"],
            ["spandex-blend", "elastane"],
        ],
        occasion: [
            ["party", "elevated", "special"],
            ["casual", "basic-casual", "everyday-work"],
            ["festive", "holiday"],
            ["workwear", "formal-work"],
            ["athletic", "athleisure"],
        ],
        activity: [
            ["festive", "holiday", "dance-and-costumes", "puja-and-vrat"],
            ["concert", "clubbing", "day-and-night"],
            ["brunch", "cocktail", "dinner-and-ceremonies"],
            ["athleisure", "walking", "leisure-sport"],
            ["travel", "beach-and-resort"],
            ["loungewear", "sleepwear", "basic-casual"],
        ],
        theme: [
            ["traditional", "spiritual", "classic"],
            ["trendy", "contemporary", "fashion"],
            ["bohemian", "nature", "dainty"],
            ["designer", "novelty"],
        ],
        neckline: [
            ["v-neck", "keyhole", "cowl"],
            ["round", "crew", "scoop"],
            ["halter", "spaghetti-straps", "one-shoulder", "off-shoulder"],
            ["square", "sweetheart", "sweetheart", "straight"],
            ["turtleneck", "mock", "high-neck"],
            ["mandarin", "camp", "polo", "button-down"],
            ["hooded", "half-zip"],
        ],
        length: [
            ["above-waist", "waist", "crop-length"],
            ["hip", "below-hip"],
            ["mid-thigh", "upper-thigh", "above-knee"],
            ["knee", "below-knee"],
            ["mid-calf", "above-ankle", "ankle"],
            ["floor", "full"],
        ],
    },
    categoryFamilies: {
        sets_family: ["sets", "set", "co-ord", "co-ords", "coord", "other-sets"],
        ethnic_family: ["ethnic", "saree", "kurta", "kurti", "lehenga", "salwar", "dhoti", "sherwani", "anarkali", "sharara", "chaniya", "dupatta", "pavadai-davani"],
        jewelry_family: ["necklace", "earring", "bracelet", "ring", "anklet", "jewellery", "jewelry", "bangle"],
        accessories_family: ["bag", "watch", "glasses", "sunglass", "wallet", "tie", "cap", "pocket-square"],
        western_family: ["t-shirt", "shirt", "top", "dress", "jeans", "trouser", "shorts", "skirt", "jumpsuit", "sweatshirt", "jacket"],
    },
};
